[tool.ruff]
line-length = 150
target-version = "py311"
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["E203", "E501", "E701", "SIM108"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
# プロジェクト名があれば↓を指定（相対順序が安定）
# known-first-party = ["fake-tools"]
